### ISSUE TITLE
Linnstrument128 low row arpeggiator triggering notes

### ISSUE THREAD

**Issue by metakeule** [rogerlinndesign/linnstrument-firmware#39]
When using the low row as an arpeggiator, the first pad pressed will be used as zero/starting point (based on the general settings) and when I keep the pad pressed and press another pad on the low row, the arpeggiator speed will be faster or lower, relative to the position of the first pad, which is nice. 

However, when pressing the second pad sometimes additional pads from the rows above are triggered. It feels like a hardware issue (the triggered pads are above), but I think it is a software issue (did not happen when not using the low row as arpeggiator).

**Comment by gitouttahea** [comment]
Hi Metakeule,

You’re probably experiencing a limitation of the sensor technology, which is stating on the Specs and FAQ pages:

• Sensor Limitations:
 > Only one touch is permitted within each note pad.
 > If 3 note pads are pressed that are 3 corners of a rectangle, presses to a note pad that is the 4th corner of that rectangle will be ignored.
 > No more than 3 note pads are permitted in the same vertical column. Pressing a 4th note pad in the same column will be ignored.
 > Y-axis (forward-backward) movement is limited to the 17 mm vertical dimension of each note pad. Sliding your finger vertically across rows will result in a new note when the touch enters the next vertical note pad.
 > Maximum simultaneous touches: about 50.
 > Minimum distance between any 2 touches: 5 mm, but the 2 touches must be in 2 adjacent note pads.

Unfortunately this is a fundamental limitation of the sensing technology that allows me to price LinnStrument for much less than would otherwise be required. However, this limitation shouldn’t trigger additional cells but rather prevent the pressing of a cell that is the fourth corner of a rectangle with 3 pressed corners. I suspect the problem is that your unit is not calibrated correctly. If so, I apologize. You can recalibrate your L128 in a about 2 minutes. In Panel Settings > Global Settings, search for “calibrate” near the bottom of the page under the heading “Actions”. 

It is possible that performing a Calibration won’t help because the specific notes and Low Row buttons that you are holding form 4 corners of a rectangle. In this case, the only solution is to find another fingering that doesn’t form 4 corners of a rectangle. For example, my design intent for the Low Row was not to press multiple buttons but rather to slide a single thumb left or right while using your fingers to play the notes above. Or, given LinnStrument’s overlapping rows of pitches, any chord can be fingered in a variety of different ways that do not cause a rectangle to be pressed. 

Roger Linn

**Comment by metakeule** [comment]
Hi Roger,

it sounds like you have hit the nail. I'll have a look.

Thanks for your efforts and this great instrument!
